FROM chuanwen/cowsay
# ADD

# ENTRYPOINT /usr/games/fortune -a | /usr/games/cowsay -f tux
# ENTRYPOINT ["/usr/games/fortune -a", "-o pipefail /usr/games/cowsay"]
# ENTRYPOINT ["/usr/games/fortune -a", "| /usr/games/cowsay"]
# ENTRYPOINT ["/usr/games/cowsay -f tux"]

CMD /usr/games/cowsay